### ISSUE TITLE
protein decay

### ISSUE THREAD

**Issue by jtyurkovich** [whole-cell-tutors/whole-cell-reduced#5]
Currently the issues are related to the naming of species

In the Excel tables, reactants and products were named as compartment.Species; these need to be changed to Species_compartment

Working through now

**Comment by manikitos** [comment]
just a copy of @binfalse's comment:
Actually, that's still a problem. I found https://github.com/whole-cell-tutors/whole-cell-reduced/blob/1371a2c17e3cd1a1abcb28f9a34a0e9ca805edff/ProteinDecay/protein-decay.py#L285

```
check(s1.setCompartment('c'), 'set species s1 compartment')
```

and expected that everything happens in `c`. turns out that some of them are actually in e.g. `m`, so we should be careful in naming the species, instead of just appending `c`. and we also need to add the missing compartments...

**Comment by manikitos** [comment]
Why can't we just use compartment name that was read from the table?
